### ISSUE TITLE
error[E0603]: module `export` is private

### ISSUE THREAD

**Issue by juristoeckli** [mum-rs/mum#83]
Compiling futures v0.3.13
   Compiling toml v0.5.8
   Compiling bincode v1.3.2
   Compiling ipc-channel v0.14.1
   Compiling mumlib v0.3.0
error[E0603]: module `export` is private
 --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/mumlib-0.3.0/src/error.rs:1:12
  |
1 | use serde::export::Formatter;
  |            ^^^^^^

error[E0603]: module `export` is private
 --> /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/mumlib-0.3.0/src/state.rs:1:12
  |
1 | use serde::export::Formatter;
  |            ^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0603`.
error: could not compile `mumlib`.
warning: build failed, waiting for other jobs to finish...
^C  Building [=====================================================> ] 173/175

**Comment by sornas** [comment]
Yeah we haven't published a new version in a while. I believe this has been fixed on main, could you try cloning and building manually?

**Comment by sornas** [comment]
I've published 0.3.1 now, see if that one works better.

**Comment by sornas** [comment]
Please let me know if it still fails and I'll re-open!

**Comment by juristoeckli** [comment]
Tanks for working on this project.
it  now works, but fails later during build.  (it probably is somehow my fault :)

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/network/tcp.rs:326:16
    |
326 |         while !matches!(
    |                ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/network/udp.rs:117:16
    |
117 |         while !matches!(
    |                ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/network/udp.rs:206:16
    |
206 |         while !matches!(
    |                ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:91:21
   |
91 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Connected) {
   |                     ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:141:21
    |
141 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Connected) {
    |                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:155:21
    |
155 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Connected) {
    |                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:213:21
    |
213 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Connected) {
    |                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:248:21
    |
248 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Connected) {
    |                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:315:21
    |
315 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Disconnected) {
    |                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:360:21
    |
360 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Connected) {
    |                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:394:21
    |
394 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Connected) {
    |                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error[E0658]: use of unstable library feature 'matches_macro'
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/mumd-0.3.1/src/state.rs:403:21
    |
403 |                 if !matches!(*self.phase_receiver().borrow(), StatePhase::Connected) {
    |                     ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to 12 previous errors

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `mumd v0.3.1`, intermediate artifacts can be found at `/tmp/cargo-installQKd3YO`

Caused by:
  could not compile `mumd`.

To learn more, run the command again with --verbose.
